// fly-brain shader for Ghostty -- GENERATED by ghostty/bake.py from
// ghostty/flybrain.template.glsl. Edit the template, not this file.
//
// ~400 real neurons of the FlyWire connectome (frontal projection), their
// strongest real synapses, and spike cascades replayed from the flyweb LIF
// simulation (first-spike latency + rate per neuron, slowed down).
//
// Typing: every cursor move (a keypress) force-fires the real neurons nearest
// the matching spot of the brain (window mapped onto it) and the baked LIF
// cascade spreads from there. Ghostty gives shaders only the last two cursor
// positions, so fast typing restarts the cascade at each key.
//
// Tweak these and reload the config (Cmd+Shift+,):
#define GLOW_STRENGTH 1.0   // overall brightness of the brain
#define BRAIN_FIT     0.94  // 1.0 = brain width fits the window
#define TEXT_KEEPOUT  0.92  // 1.0 = no glow at all on/next to glyphs
#define TYPING_GAIN   1.0   // 0.0 disables the typing response
#define TYPING_PULSES 1     // 0 = typing lights neurons only (cheaper on the GPU)

//@@DATA@@

const vec3 KIND_COLOR[4] = vec3[4](
    vec3(0.20, 0.62, 1.00),   // acetylcholine (excitatory)
    vec3(1.00, 0.28, 0.62),   // GABA (inhibitory)
    vec3(1.00, 0.68, 0.20),   // glutamate
    vec3(0.35, 1.00, 0.62)    // monoamines
);

float hash11(float n) { return fract(sin(n * 127.1) * 43758.5453); }

// sparse spontaneous flicker so the brain is never perfectly still
float ambient(int j) {
    float ph = iTime * 0.35 + hash11(float(j)) * 50.0;
    float r = hash11(float(j) * 7.13 + floor(ph) * 3.7);
    return r < 0.10 ? exp(-fract(ph) / 0.35 / 0.30) * 0.55 : 0.0;
}

// Channels 0..NW-1 are the ambient sensory waves; NW is the current cursor
// event and NW+1 the previous one.
#define NCH (NW + 2)
int gHubA[2];
int gHubB[2];

// first-spike time of neuron j in channel m, seconds since the channel started
float arrival(int m, int j) {
    if (m < NW) return WAVE[m * NN + j].x;
    int c = m - NW;
    int i0 = gHubA[c] * NN + j;
    int i1 = gHubB[c] * NN + j;
    int q0 = int((TYP[i0 >> 2] >> uint((i0 & 3) * 8)) & 255u);
    int q1 = int((TYP[i1 >> 2] >> uint((i1 & 3) * 8)) & 255u);
    int q = min(q0, q1);
    return q >= 255 ? -1.0 : float(q) * 0.01;
}

// how strongly neuron j is spiking right now in channel m (0..1)
float spike(int m, int j, float tl) {
    float t0 = arrival(m, j);
    if (t0 < 0.0) return 0.0;
    float age = tl - t0;
    if (age < 0.0) return 0.0;
    if (m < NW) {
        vec3 w = WAVE[m * NN + j];
        if (w.y > 0.0) age -= min(floor(age / w.y), w.z - 1.0) * w.y;
        return exp(-age / 0.28);
    }
    return exp(-age / 0.22);
}

// window position -> the two nearest cascade cells (nearest, and its
// neighbour across the closest cell boundary, so movement blends smoothly)
void hubsFor(vec2 u, out int a, out int b) {
    vec2 g = clamp(u, 0.001, 0.999) * vec2(float(HX), float(HY));
    ivec2 i = ivec2(floor(g));
    vec2 f = g - vec2(i);
    ivec2 k = i;
    if (abs(f.x - 0.5) > abs(f.y - 0.5)) k.x += f.x < 0.5 ? -1 : 1;
    else k.y += f.y < 0.5 ? -1 : 1;
    k = clamp(k, ivec2(0), ivec2(HX - 1, HY - 1));
    a = i.y * HX + i.x;
    b = k.y * HX + k.x;
}

// faint neuropil haze: blurred density of all 139k neurons, bilinear
float haze(vec2 p) {
    vec2 g = (p - DMIN) / DSTEP - 0.5;
    ivec2 i = ivec2(floor(g));
    if (i.x < 0 || i.y < 0 || i.x >= DX - 1 || i.y >= DY - 1) return 0.0;
    vec2 f = fract(g);
    int k = i.y * DX + i.x;
    return mix(mix(DENS[k], DENS[k + 1], f.x),
               mix(DENS[k + DX], DENS[k + DX + 1], f.x), f.y);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 res = iResolution.xy;
    vec4 term = texture(iChannel0, fragCoord / res);

    float scale = min(res.x, res.y / ASPECT) * BRAIN_FIT;   // px per brain-width
    float pxu = 1.0 / scale;                                // one pixel, brain units
    vec2 p = (fragCoord - 0.5 * res) / scale;

    // ---- cursor events -> typing channels ---------------------------------
    float tcur = -1.0, tprev = -1.0;
    vec2 bloomP = vec2(0.0);
    float bloom = 0.0;
    gHubA[0] = gHubB[0] = gHubA[1] = gHubB[1] = 0;
    if (TYPING_GAIN > 0.0 && iCurrentCursor.z > 0.0) {
        // xy is the cursor's left / bottom edge, y down (Ghostty on Metal)
        vec2 uc = vec2(iCurrentCursor.x + 0.5 * iCurrentCursor.z,
                       iCurrentCursor.y - 0.5 * iCurrentCursor.w) / res;
        float age = iTime - iTimeCursorChange;
        if (age >= 0.0 && age < TYP_DUR) {
            tcur = age;
            hubsFor(uc, gHubA[0], gHubB[0]);
            bloomP = (uc - 0.5) * vec2(1.0, ASPECT) * HMAP;
            bloom = exp(-age / 0.30);
        }
        // Ghostty does not say when the previous cursor position was set;
        // assume one typing beat (0.15 s) before the current one.
        if (iPreviousCursor.z > 0.0 && iPreviousCursor.xy != iCurrentCursor.xy
            && age + 0.15 < TYP_DUR) {
            vec2 up = vec2(iPreviousCursor.x + 0.5 * iPreviousCursor.z,
                           iPreviousCursor.y - 0.5 * iPreviousCursor.w) / res;
            tprev = age + 0.15;
            hubsFor(up, gHubA[1], gHubB[1]);
        }
    }

    int mEnd = (tcur >= 0.0 || tprev >= 0.0) ? NCH : NW;   // typing channels only while active

    float hz = haze(p);
    vec3 glow = vec3(0.09, 0.19, 0.40) * hz * (0.55 + 0.10 * sin(iTime * 0.4 + p.x * 5.0));
    if (bloom > 0.0) {
        vec2 bd = p - bloomP;
        glow += vec3(0.45, 0.80, 1.0) * exp(-dot(bd, bd) / 0.0018) * bloom * 0.9 * TYPING_GAIN;
    }
    ivec2 c = ivec2(floor((p - GMIN) / CELL));

    if (c.x >= 0 && c.y >= 0 && c.x < GX && c.y < GY) {
        int ci = c.y * GX + c.x;

        // local time of each channel; < 0 means idle
        float tw[NCH];
        for (int m = 0; m < NW; m++) {
            float t = mod(iTime - float(m) * STAGGER, LOOP);
            tw[m] = t < WAVE_DUR ? t : -1.0;
        }
        tw[NW] = tcur;
        tw[NW + 1] = tprev;

        // ---- synapses: faint static lines + travelling spikes ------------
        for (int k = CELL_E_START[ci]; k < CELL_E_START[ci + 1]; k++) {
            int e = CELL_E[k];
            int ia = EDGE[e].x, ib = EDGE[e].y;
            vec2 a = NPOS[ia], b = NPOS[ib];
            vec2 ab = b - a;
            float len = length(ab);
            float h = clamp(dot(p - a, ab) / (len * len), 0.0, 1.0);
            vec2 q = p - (a + ab * h);
            float d2 = dot(q, q);
            if (d2 > 4.84e-4) continue;
            vec3 col = KIND_COLOR[NKIND[ia]];

            float sl = max(0.0016, pxu * 0.9);
            float amb = 0.045 + 0.06 * EW[e];
            float pulse = 0.0;
            float sp = max(0.0042, pxu * 1.2);
            for (int m = 0; m < (TYPING_PULSES == 1 ? mEnd : NW); m++) {
                if (tw[m] < 0.0) continue;
                float ta = arrival(m, ia), tb = arrival(m, ib);
                if (ta < 0.0 || tb <= ta) continue;
                float trv = clamp(tb - ta, m < NW ? 0.20 : 0.10, m < NW ? 0.90 : 0.45);
                float s = (tw[m] - (tb - trv)) / trv;
                if (s <= 0.0 || s >= 1.15) continue;
                float along = (s - h) * len;
                float tailv = along >= 0.0 ? exp(-along / 0.035)
                                           : exp(-along * along / 1.6e-5);
                float fade = smoothstep(0.0, 0.06, s) * (1.0 - smoothstep(0.95, 1.15, s));
                pulse += tailv * fade * (0.55 + 0.6 * EW[e]);
            }
            float line = exp(-d2 / (2.0 * sl * sl)) * amb;
            float halo = exp(-d2 / (2.0 * sp * sp)) * pulse;
            glow += col * line + mix(col, vec3(1.0), 0.45) * halo * 1.15;
        }

        // ---- neurons -----------------------------------------------------
        for (int k = CELL_N_START[ci]; k < CELL_N_START[ci + 1]; k++) {
            int j = CELL_N[k];
            vec2 d = p - NPOS[j];
            float r2 = dot(d, d);
            if (r2 > 0.0016) continue;

            float act = ambient(j);
            for (int m = 0; m < mEnd; m++) {
                if (tw[m] >= 0.0) act = max(act, spike(m, j, tw[m]));
            }
            float near = 1.0 - 0.45 * NDEPTH[j];
            float rc = max(0.0030 * near, pxu * 1.3);
            float sg = 0.0075 * (1.0 + 0.9 * act);
            float core = exp(-r2 / (2.0 * rc * rc));
            float halo = exp(-r2 / (2.0 * sg * sg));
            vec3 col = KIND_COLOR[NKIND[j]];
            glow += near * (col * (core * (0.30 + 0.85 * act) + halo * (0.07 + 0.42 * act))
                            + vec3(1.0) * core * act * 0.35);
        }
    }

    // soft tone-map so bright overlaps never blow out
    glow = (1.0 - exp(-glow * 1.6)) * 0.34 * GLOW_STRENGTH;

    // ---- keep text readable: no glow on glyphs or in a thin halo around them.
    // The background colour is read from the window-padding corners of the
    // terminal texture (the corner that agrees most with the other three)
    // rather than from iBackgroundColor, which Ghostty only fills in after the
    // terminal state changes and which is zero until then.
    float ink = 0.0;
    if (max(glow.r, max(glow.g, glow.b)) > 0.003) {
        vec3 k0 = texture(iChannel0, vec2(1.5, 1.5) / res).rgb;
        vec3 k1 = texture(iChannel0, vec2(res.x - 1.5, 1.5) / res).rgb;
        vec3 k2 = texture(iChannel0, vec2(1.5, res.y - 1.5) / res).rgb;
        vec3 k3 = texture(iChannel0, (res - 1.5) / res).rgb;
        float s0 = distance(k0, k1) + distance(k0, k2) + distance(k0, k3);
        float s1 = distance(k1, k0) + distance(k1, k2) + distance(k1, k3);
        float s2 = distance(k2, k0) + distance(k2, k1) + distance(k2, k3);
        float s3 = distance(k3, k0) + distance(k3, k1) + distance(k3, k2);
        vec3 bg = k0; float sb = s0;
        if (s1 < sb) { bg = k1; sb = s1; }
        if (s2 < sb) { bg = k2; sb = s2; }
        if (s3 < sb) { bg = k3; }
        for (int i = 0; i < 5; i++) {
            vec2 o = i == 0 ? vec2(0.0) : vec2(i == 1 ? 1.8 : (i == 2 ? -1.8 : 0.0),
                                               i == 3 ? 1.8 : (i == 4 ? -1.8 : 0.0));
            vec3 s = texture(iChannel0, (fragCoord + o) / res).rgb;
            ink = max(ink, smoothstep(0.03, 0.14, distance(s, bg)));
        }
    }
    glow *= 1.0 - TEXT_KEEPOUT * ink;

    fragColor = vec4(term.rgb + glow, term.a);
}
