// fly-brain shader for Ghostty -- GENERATED by ghostty/bake.py from
// ghostty/flybrain.template.glsl. Edit the template, not this file.
//
// ~400 real neurons of the FlyWire connectome (frontal projection), their
// strongest real synapses, and spike cascades replayed from the flyweb LIF
// simulation (first-spike latency + rate per neuron, slowed down).
//
// Tweak these three and reload the config (Cmd+Shift+,):
#define GLOW_STRENGTH 1.0   // overall brightness of the brain
#define BRAIN_FIT     0.94  // 1.0 = brain width fits the window
#define TEXT_KEEPOUT  0.92  // 1.0 = no glow at all on/next to glyphs

//@@DATA@@

const vec3 KIND_COLOR[4] = vec3[4](
    vec3(0.20, 0.62, 1.00),   // acetylcholine (excitatory)
    vec3(1.00, 0.28, 0.62),   // GABA (inhibitory)
    vec3(1.00, 0.68, 0.20),   // glutamate
    vec3(0.35, 1.00, 0.62)    // monoamines
);

float hash11(float n) { return fract(sin(n * 127.1) * 43758.5453); }

// sparse spontaneous flicker so the brain is never perfectly still
float ambient(int j) {
    float ph = iTime * 0.35 + hash11(float(j)) * 50.0;
    float r = hash11(float(j) * 7.13 + floor(ph) * 3.7);
    return r < 0.10 ? exp(-fract(ph) / 0.35 / 0.30) * 0.55 : 0.0;
}

// how strongly neuron j is spiking right now in wave m (0..1)
float spike(int m, int j, float tl) {
    vec3 w = WAVE[m * NN + j];
    if (w.x < 0.0) return 0.0;
    float age = tl - w.x;
    if (age < 0.0) return 0.0;
    if (w.y > 0.0) {
        float k = min(floor(age / w.y), w.z - 1.0);
        age -= k * w.y;
    }
    return exp(-age / 0.28);
}

// faint neuropil haze: blurred density of all 139k neurons, bilinear
float haze(vec2 p) {
    vec2 g = (p - DMIN) / DSTEP - 0.5;
    ivec2 i = ivec2(floor(g));
    if (i.x < 0 || i.y < 0 || i.x >= DX - 1 || i.y >= DY - 1) return 0.0;
    vec2 f = fract(g);
    int k = i.y * DX + i.x;
    return mix(mix(DENS[k], DENS[k + 1], f.x),
               mix(DENS[k + DX], DENS[k + DX + 1], f.x), f.y);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 res = iResolution.xy;
    vec4 term = texture(iChannel0, fragCoord / res);

    float scale = min(res.x, res.y / ASPECT) * BRAIN_FIT;   // px per brain-width
    float pxu = 1.0 / scale;                                // one pixel, brain units
    vec2 p = (fragCoord - 0.5 * res) / scale;

    float hz = haze(p);
    vec3 glow = vec3(0.09, 0.19, 0.40) * hz * (0.55 + 0.10 * sin(iTime * 0.4 + p.x * 5.0));
    ivec2 c = ivec2(floor((p - GMIN) / CELL));

    if (c.x >= 0 && c.y >= 0 && c.x < GX && c.y < GY) {
        int ci = c.y * GX + c.x;

        // local time of each wave in its loop slot; < 0 means idle
        float tw[NW];
        for (int m = 0; m < NW; m++) {
            float t = mod(iTime - float(m) * STAGGER, LOOP);
            tw[m] = t < WAVE_DUR ? t : -1.0;
        }

        // ---- synapses: faint static lines + travelling spikes ------------
        for (int k = CELL_E_START[ci]; k < CELL_E_START[ci + 1]; k++) {
            int e = CELL_E[k];
            int ia = EDGE[e].x, ib = EDGE[e].y;
            vec2 a = NPOS[ia], b = NPOS[ib];
            vec2 ab = b - a;
            float len = length(ab);
            float h = clamp(dot(p - a, ab) / (len * len), 0.0, 1.0);
            vec2 q = p - (a + ab * h);
            float d2 = dot(q, q);
            if (d2 > 4.84e-4) continue;
            vec3 col = KIND_COLOR[NKIND[ia]];

            float sl = max(0.0016, pxu * 0.9);
            float amb = 0.045 + 0.06 * EW[e];
            float pulse = 0.0;
            float sp = max(0.0042, pxu * 1.2);
            for (int m = 0; m < NW; m++) {
                if (tw[m] < 0.0) continue;
                float ta = WAVE[m * NN + ia].x, tb = WAVE[m * NN + ib].x;
                if (ta < 0.0 || tb <= ta) continue;
                float trv = clamp(tb - ta, 0.20, 0.90);
                float s = (tw[m] - (tb - trv)) / trv;
                if (s <= 0.0 || s >= 1.15) continue;
                float along = (s - h) * len;
                float tailv = along >= 0.0 ? exp(-along / 0.035)
                                           : exp(-along * along / 1.6e-5);
                float fade = smoothstep(0.0, 0.06, s) * (1.0 - smoothstep(0.95, 1.15, s));
                pulse += tailv * fade * (0.55 + 0.6 * EW[e]);
            }
            float line = exp(-d2 / (2.0 * sl * sl)) * amb;
            float halo = exp(-d2 / (2.0 * sp * sp)) * pulse;
            glow += col * line + mix(col, vec3(1.0), 0.45) * halo * 1.15;
        }

        // ---- neurons -----------------------------------------------------
        for (int k = CELL_N_START[ci]; k < CELL_N_START[ci + 1]; k++) {
            int j = CELL_N[k];
            vec2 d = p - NPOS[j];
            float r2 = dot(d, d);
            if (r2 > 0.0016) continue;

            float act = ambient(j);
            for (int m = 0; m < NW; m++) {
                if (tw[m] >= 0.0) act = max(act, spike(m, j, tw[m]));
            }
            float near = 1.0 - 0.45 * NDEPTH[j];
            float rc = max(0.0030 * near, pxu * 1.3);
            float sg = 0.0075 * (1.0 + 0.9 * act);
            float core = exp(-r2 / (2.0 * rc * rc));
            float halo = exp(-r2 / (2.0 * sg * sg));
            vec3 col = KIND_COLOR[NKIND[j]];
            glow += near * (col * (core * (0.30 + 0.85 * act) + halo * (0.07 + 0.42 * act))
                            + vec3(1.0) * core * act * 0.35);
        }
    }

    // soft tone-map so bright overlaps never blow out
    glow = (1.0 - exp(-glow * 1.6)) * 0.34 * GLOW_STRENGTH;

    // ---- keep text readable: no glow on glyphs or in a thin halo around them.
    // The background colour is read from the window-padding corners of the
    // terminal texture (the corner that agrees most with the other three)
    // rather than from iBackgroundColor, which Ghostty only fills in after the
    // terminal state changes and which is zero until then.
    float ink = 0.0;
    if (max(glow.r, max(glow.g, glow.b)) > 0.003) {
        vec3 k0 = texture(iChannel0, vec2(1.5, 1.5) / res).rgb;
        vec3 k1 = texture(iChannel0, vec2(res.x - 1.5, 1.5) / res).rgb;
        vec3 k2 = texture(iChannel0, vec2(1.5, res.y - 1.5) / res).rgb;
        vec3 k3 = texture(iChannel0, (res - 1.5) / res).rgb;
        float s0 = distance(k0, k1) + distance(k0, k2) + distance(k0, k3);
        float s1 = distance(k1, k0) + distance(k1, k2) + distance(k1, k3);
        float s2 = distance(k2, k0) + distance(k2, k1) + distance(k2, k3);
        float s3 = distance(k3, k0) + distance(k3, k1) + distance(k3, k2);
        vec3 bg = k0; float sb = s0;
        if (s1 < sb) { bg = k1; sb = s1; }
        if (s2 < sb) { bg = k2; sb = s2; }
        if (s3 < sb) { bg = k3; }
        for (int i = 0; i < 5; i++) {
            vec2 o = i == 0 ? vec2(0.0) : vec2(i == 1 ? 1.8 : (i == 2 ? -1.8 : 0.0),
                                               i == 3 ? 1.8 : (i == 4 ? -1.8 : 0.0));
            vec3 s = texture(iChannel0, (fragCoord + o) / res).rgb;
            ink = max(ink, smoothstep(0.03, 0.14, distance(s, bg)));
        }
    }
    glow *= 1.0 - TEXT_KEEPOUT * ink;

    fragColor = vec4(term.rgb + glow, term.a);
}
